#!/usr/bin/env node
// Regenerate the compact active index in a Context directory's AGENTS.md,
// validate active markup frontmatter, check Markdown links, say when a consolidation
// pass is due, and keep Context-Inbox out of Git.
//
// Usage: node scripts/index.mjs <path-to-Context> [--nested] [--links=<folder>] [--check] [--consolidated[=YYYY-MM-DD]] [--cadence=<days>] [--force]
//
// The block is guard-delimited and idempotent. Content outside the block is
// preserved. Every Archive folder is left out of the active index at any depth. The
// consolidation marker is one comment line directly above the block, outside the
// guards, so an older copy of this script leaves it alone, and the folders --links
// named sit in a second comment line under it. The script knows only its current
// name: after a rename, every existing index is regenerated by hand.

import { readFileSync, writeFileSync, appendFileSync, existsSync, readdirSync, statSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { join, relative, resolve, basename, extname, dirname, isAbsolute } from "node:path";

const SKILL_NAME = "context-memory";
const BEGIN = `<!-- BEGIN ${SKILL_NAME} index (generated, do not edit) -->`;
const END = `<!-- END ${SKILL_NAME} index -->`;
const escape = (t) => t.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
const GUARD = new RegExp(`${escape(BEGIN)}[\\s\\S]*?${escape(END)}`);
const MARKER = new RegExp(`<!-- ${escape(SKILL_NAME)}: last consolidation pass (\\d{4}-\\d{2}-\\d{2}|none), cadence (\\d+) days -->\\r?\\n?`);
const LINK_ROOTS = new RegExp(`<!-- ${escape(SKILL_NAME)}: also check links in ((?:<[^<>\\n]+>(?:, )?)+) -->\\r?\\n?`);
const MARKUP = new Set([".md", ".html"]);
const ARCHIVE = "Archive";
const TEMP = "Context-Inbox";
const PLACEHOLDERS = new Set([".gitkeep", ".gitignore", ".DS_Store", "Thumbs.db"]);
const REQUIRED = ["name", "description", "date_created", "date_modified"];
const DATE = /^\d{4}-\d{2}-\d{2}$/;
const INDEX_WARNING_BYTES = 24 * 1024;
const INDEX_ENTRIES_REVIEW = 200;
const COMBINED_WARNING_BYTES = 32 * 1024;
// Prompts to look, not limits to enforce, so they warn and never fail the run.
const ROOT_FILES_REVIEW = 8;
const DIR_FILES_REVIEW = 12;
const DIR_FILES_SUBTOPIC = 20;
const DESCRIPTION_REVIEW_CHARS = 300;
const DESCRIPTION_MAX_CHARS = 1024;
// A consolidation pass is due on this calendar cadence even when nothing else fired,
// because drift between documents is the one thing this script cannot see.
const DEFAULT_CADENCE_DAYS = 7;
// How many directory levels below the Context's parent --nested looks for other
// Context directories that already carry an index.
const NESTED_DEPTH = 2;
const NESTED_SKIP = new Set([ARCHIVE, TEMP, "node_modules"]);
// Folders the link check never enters. An inbox is on its way out, so its own links
// are not worth fixing. Other hidden folders are read, because instruction files that
// link into Context often live in one.
const LINK_SKIP = new Set([TEMP, "node_modules", ".git"]);
const KNOWN_FLAGS = ["--help", "--force", "--nested", "--consolidated", "--check"];

if (process.argv.includes("--help")) {
  console.log(
    "Usage: node scripts/index.mjs <path-to-Context> [--nested] [--links=<folder>] [--check] [--consolidated[=YYYY-MM-DD]] [--cadence=<days>] [--force]\n" +
      "Regenerates the compact active index in <path>/AGENTS.md, validates active frontmatter, warns about Context-Inbox, directory density, description shape, and Markdown links that do not resolve, says when a consolidation pass is due, and adds Context-Inbox/ to the repository's .gitignore when it is missing. Every Archive folder is left out of the active index. Exits 1 on active errors.\n" +
      "Links: every inline Markdown link with a relative target is checked in every Markdown file under Context, Archive included. In the other Markdown files of the folder that holds Context, hidden folders included, only links that point into this Context or its Context-Inbox are checked. Letter case must match. Web addresses, absolute paths, same-file anchors, code, HTML blocks and comments, and reference-style links are not checked, and the part after # is ignored. A character written as a named reference other than amp, lt, gt, quot, or apos is not decoded, so write the character itself or percent-encode it.\n" +
      "  --nested            Also process every indexed Context directory in project folders up to two levels below this one's parent, each on its own.\n" +
      "  --links=<folder>    Also look in this folder, such as a sibling repository or the rest of a project whose Context sits in a subfolder, for links into this Context, remembered for this Context. Repeat it to name several. --links=none forgets them.\n" +
      "  --check             Report only and write nothing: no index, no Archive index, no .gitignore line, nothing remembered. With it, --links applies to this run only, and --consolidated and --cadence are refused.\n" +
      "  --consolidated      Record that a consolidation pass finished today, or on the given date, for this Context only. Refused while this Context has errors, a Context-Inbox with files, or a Markdown link that does not resolve.\n" +
      "  --cadence=<days>    Days between consolidation passes before one is due, remembered for this Context. Default 7. 0 turns the calendar check off.\n" +
      "  --force             Allow a directory not named Context.",
  );
  process.exit(0);
}

const flags = process.argv.slice(2).filter((a) => a.startsWith("--"));
const args = process.argv.slice(2).filter((a) => !a.startsWith("--"));
for (const flag of flags) {
  const ok = KNOWN_FLAGS.includes(flag) || /^--consolidated=\d{4}-\d{2}-\d{2}$/.test(flag) || /^--cadence=\d+$/.test(flag) || /^--links=[^<>]+$/.test(flag);
  if (!ok) {
    console.error(`ERROR: unknown or malformed flag ${flag}. Run --help.`);
    process.exit(1);
  }
}
const force = flags.includes("--force");
const nested = flags.includes("--nested");
const cadenceFlag = flags.find((a) => a.startsWith("--cadence="));
const cadenceArg = cadenceFlag ? Number(cadenceFlag.slice("--cadence=".length)) : null;
const consolidatedFlag = flags.find((a) => a.startsWith("--consolidated"));
const checkOnly = flags.includes("--check");
const linksArg = flags.filter((a) => a.startsWith("--links=")).map((a) => a.slice("--links=".length));
if (checkOnly && (consolidatedFlag || cadenceFlag)) {
  console.error("ERROR: --check writes nothing, so it cannot record a pass or a cadence. Drop --check, or drop --consolidated and --cadence.");
  process.exit(1);
}
if (linksArg.length > 1 && linksArg.includes("none")) {
  console.error("ERROR: --links=none forgets every folder, so it cannot sit beside another --links.");
  process.exit(1);
}

const today = localDate(new Date());
let consolidatedOn = null;
if (consolidatedFlag) {
  consolidatedOn = consolidatedFlag.includes("=") ? consolidatedFlag.slice("--consolidated=".length) : today;
  if (!isRealDate(consolidatedOn) || consolidatedOn > today) {
    console.error("ERROR: --consolidated takes a real YYYY-MM-DD date no later than today");
    process.exit(1);
  }
}

const root = resolve(args[0] ?? "./Context");
if (!existsSync(root) || !statSync(root).isDirectory()) {
  console.error(`ERROR: ${root} is not a directory`);
  process.exit(1);
}
if (basename(root) !== "Context" && !force) {
  console.error(
    `ERROR: ${root} is not named Context. The index block belongs only in a Context directory's AGENTS.md. Pass --force to override.`,
  );
  process.exit(1);
}

function localDate(d) {
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;
}

function isRealDate(value) {
  const date = new Date(`${value}T00:00:00Z`);
  return DATE.test(value) && !Number.isNaN(date.getTime()) && date.toISOString().slice(0, 10) === value;
}

function daysBetween(from, to) {
  return Math.round((new Date(`${to}T00:00:00Z`) - new Date(`${from}T00:00:00Z`)) / 86400000);
}

// Reads the top-level scalar fields. Nested mappings, lists, and block scalars under
// any other key are accepted without being read, so a document may keep the fields
// it arrived with under `metadata:`. The four required fields must be single-line.
function parseFrontmatter(raw, ext) {
  let block = null;
  if (ext === ".md") {
    const match = raw.match(/^---\r?\n([\s\S]*?)\r?\n---/);
    if (match) block = match[1];
  } else {
    const match = raw.match(/^<!--\r?\n([\s\S]*?)\r?\n-->/);
    if (match) block = match[1].replace(/^---\r?\n/, "").replace(/\r?\n---$/, "");
  }
  if (block === null) return null;

  const fields = {};
  const badLines = [];
  for (const line of block.split(/\r?\n/)) {
    if (!line.trim()) continue;
    if (/^\s/.test(line) || line.startsWith("- ")) continue;
    const match = line.match(/^([\w-]+):\s*(.*)$/);
    if (!match) {
      badLines.push(line.trim());
      continue;
    }
    const key = match[1];
    const value = match[2].trim();
    if (/^[|>][+-]?$/.test(value)) {
      if (REQUIRED.includes(key)) badLines.push(`${key}: block scalars are unsupported here, use a single-line value`);
      continue;
    }
    fields[key] = value.replace(/^"(.*)"$/s, "$1").replace(/^'(.*)'$/s, "$1");
  }
  return { fields, badLines };
}

// Files under a directory, ignoring only placeholder files such as .gitkeep.
function listFiles(dir, out = []) {
  for (const entry of readdirSync(dir).sort()) {
    if (PLACEHOLDERS.has(entry)) continue;
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) listFiles(full, out);
    else out.push(entry);
  }
  return out;
}

function hasIndex(contextDir) {
  const agents = join(contextDir, "AGENTS.md");
  return existsSync(agents) && readFileSync(agents, "utf8").includes(BEGIN);
}

function findNestedContexts(parent, depth, found, skipped) {
  if (depth === 0) return;
  for (const entry of readdirSync(parent).sort()) {
    if (entry.startsWith(".") || NESTED_SKIP.has(entry)) continue;
    const full = join(parent, entry);
    let isDir = false;
    try {
      isDir = statSync(full).isDirectory();
    } catch {
      continue;
    }
    if (!isDir) continue;
    if (entry === "Context") {
      if (resolve(full) === root) continue;
      if (hasIndex(full)) found.push(full);
      else skipped.push(full);
      continue;
    }
    findNestedContexts(full, depth - 1, found, skipped);
  }
}

// Blanks out the parts of a document that are not read as Markdown: fenced and indented
// code, HTML blocks, code spans, and HTML comments. Line endings and length are kept, so
// positions still match. An indented line counts as code only after a blank line and
// outside a list, because a paragraph under a list item is indented the same way.
function maskCode(text) {
  const blank = (part) => part.replace(/[^\n]/g, " ");
  let fence = null;
  let html = false;
  let inList = false;
  let afterBlank = true;
  let indented = false;
  let out = text
    .split("\n")
    .map((line) => {
      const mark = line.match(/^(?:[ \t>]|[-*+][ \t]|\d+[.)][ \t])*(`{3,}|~{3,})(.*)$/);
      if (fence) {
        if (mark && mark[1][0] === fence[0] && mark[1].length >= fence.length && !mark[2].trim()) fence = null;
        return blank(line);
      }
      if (mark && !(mark[1][0] === "`" && mark[2].includes("`"))) {
        fence = mark[1];
        return blank(line);
      }
      if (!line.trim()) {
        html = false;
        afterBlank = true;
        return line;
      }
      const deep = /^(?: {4}|\t)/.test(line);
      if (!deep) inList = /^ {0,3}(?:[-*+]|\d+[.)])[ \t]/.test(line);
      indented = deep && !inList && (afterBlank || indented);
      afterBlank = false;
      if (!deep && /^ {0,3}<\/?(?:div|table|pre|script|style|details|summary|section|article|p|ul|ol|li|dl|blockquote|figure|form|h[1-6])(?:[\s/>]|$)/i.test(line)) html = true;
      return html || indented ? blank(line) : line;
    })
    .join("\n");
  // A code span opens and closes with backtick runs of the same length, inside one paragraph.
  for (let i = 0; i < out.length; i++) {
    if (out[i] === "\\") i++;
    else if (out[i] === "`") {
      let run = 1;
      while (out[i + run] === "`") run++;
      const rest = out.slice(i + run);
      const paragraph = rest.search(/\n[ \t]*\n/);
      const close = rest.search(new RegExp("(?<!`)`{" + run + "}(?!`)"));
      if (close !== -1 && (paragraph === -1 || close < paragraph)) {
        const end = i + run + close + run;
        out = out.slice(0, i) + blank(out.slice(i, end)) + out.slice(end);
        i = end - 1;
      } else i += run - 1;
    }
  }
  // Comments are blanked last, so a comment mark inside code does not open one.
  return out.replace(/<!--[\s\S]*?-->/g, blank);
}

// Reads the destination of an inline link that opens at `start`, just past "](". Returns
// the target and where the link closes, or null when what follows is not a link. Follows
// CommonMark: a destination in angle brackets or with balanced parentheses, an optional
// title, and at most one line ending between the parts.
function linkDestination(text, start) {
  const gap = (from) => {
    const space = text.slice(from).match(/^[ \t]*(?:\n[ \t]*)?/)[0];
    return from + space.length;
  };
  let i = gap(start);
  let target = "";
  if (text[i] === "<") {
    for (i++; text[i] !== ">"; i++) {
      if (i >= text.length || text[i] === "\n" || text[i] === "<") return null;
      if (text[i] === "\\" && i + 1 < text.length) target += text[i++];
      target += text[i];
    }
    i++;
  } else {
    let depth = 0;
    for (; i < text.length && !/\s/.test(text[i]); i++) {
      if (text[i] === "\\" && i + 1 < text.length) target += text[i++];
      else if (text[i] === "(") depth++;
      else if (text[i] === ")" && depth-- === 0) break;
      target += text[i];
    }
    if (!target || depth > 0) return null;
  }
  const afterTarget = i;
  i = gap(i);
  const closer = { '"': '"', "'": "'", "(": ")" }[text[i]];
  if (closer && i > afterTarget) {
    for (i++; text[i] !== closer; i++) {
      if (i >= text.length || /^\n[ \t]*\n/.test(text.slice(i))) return null;
      if (text[i] === "\\") i++;
    }
    i = gap(i + 1);
  }
  return text[i] === ")" ? { target, end: i } : null;
}

// Inline Markdown links and images in a document, as { line, target }. Code and HTML
// comments are skipped, so a path that is meant as text and not as a link goes in a
// code span. Reference-style definitions are not read, because a transcript line such
// as "[Name]: word" has the same shape.
function markdownLinks(text) {
  const masked = maskCode(text.replace(/\r\n/g, "\n"));
  const found = [];
  let open = 0;
  let line = 1;
  for (let i = 0; i < masked.length; i++) {
    const char = masked[i];
    if (char === "\n") {
      line++;
      if (/^[ \t]*(\n|$)/.test(masked.slice(i + 1, i + 200))) open = 0;
    } else if (char === "\\") i++;
    else if (char === "[") open++;
    else if (char === "]" && open) {
      open--;
      const link = masked[i + 1] === "(" ? linkDestination(masked, i + 2) : null;
      if (link) {
        found.push({ line, target: link.target });
        line +=(masked.slice(i, link.end).match(/\n/g) ?? []).length;
        i = link.end;
      }
    }
  }
  return found;
}

// Undoes Markdown's backslash escapes and character references in a link target, in
// source order, so an escaped ampersand does not start a reference. Numeric references
// and the five XML names are decoded. Other named references are left as written.
function unescapeTarget(target) {
  const named = { amp: "&", lt: "<", gt: ">", quot: '"', apos: "'" };
  const point = (code, whole) => (code > 0 && code <= 0x10ffff ? String.fromCodePoint(code) : whole);
  return target.replace(/\\([!-/:-@[-`{-~])|&(?:#(\d{1,7})|#[xX]([0-9a-fA-F]{1,6})|(amp|lt|gt|quot|apos));/g, (whole, escaped, dec, hex, name) =>
    escaped ?? (name ? named[name] : point(dec ? Number(dec) : parseInt(hex, 16), whole)),
  );
}

// The file path a link target names, or null when the target is not a relative path:
// a web or mail address, any other scheme, a drive or root path, or an anchor in the
// same file. The part after # is dropped, since heading anchors differ by renderer.
function relativePath(target) {
  const path = target.trim().replace(/#.*$/, "");
  if (!path || /^[A-Za-z][A-Za-z0-9+.-]*:/.test(path) || path.startsWith("/") || path.startsWith("\\")) return null;
  return path;
}

const listings = new Map();
// The index file a run is about to write, which counts as present on a first run.
let pendingIndex = null;
function listing(dir) {
  if (!listings.has(dir)) {
    try {
      listings.set(dir, new Set(readdirSync(dir)));
    } catch {
      listings.set(dir, null);
    }
  }
  return listings.get(dir);
}

// Walks a relative path one segment at a time against real directory listings, so a
// target that differs only in letter case fails here even where the file system would
// open it. Returns null when it resolves, and otherwise the name that was found in
// another letter case, or "" when nothing matched.
function unresolved(fromDir, path) {
  let dir = fromDir;
  for (const segment of path.split("/")) {
    if (!segment || segment === ".") continue;
    if (segment === "..") {
      dir = dirname(dir);
      continue;
    }
    const names = listing(dir);
    if (!names) return "";
    if (join(dir, segment) === pendingIndex) return null;
    if (!names.has(segment)) return [...names].find((name) => name.toLowerCase() === segment.toLowerCase()) ?? "";
    dir = join(dir, segment);
  }
  // A listed name can still be a link to something that is gone, and a path that ends
  // in a slash names a folder.
  let target = null;
  try {
    target = statSync(dir);
  } catch {
    return "";
  }
  return path.endsWith("/") && !target.isDirectory() ? "" : null;
}

function isInside(path, dir) {
  const rel = relative(dir, path);
  return !rel.startsWith("..") && !isAbsolute(rel);
}

// The links in one Markdown file whose relative target does not resolve. `only` limits
// the report to targets inside the given folders, and `text` is the file's content when
// the caller has already read it.
function brokenLinks(file, { only = null, text = null } = {}) {
  const dir = dirname(file);
  const broken = [];
  for (const { line, target } of markdownLinks(text ?? readFileSync(file, "utf8"))) {
    const path = relativePath(unescapeTarget(target));
    if (path === null) continue;
    const candidates = [path];
    try {
      const decoded = decodeURIComponent(path);
      if (decoded !== path) candidates.push(decoded);
    } catch {
      // Not percent-encoded, so the literal path is the only reading.
    }
    for (const candidate of [...candidates]) if (candidate.includes("?")) candidates.push(candidate.replace(/\?.*$/, ""));
    const misses = candidates.map((candidate) => unresolved(dir, candidate));
    if (misses.includes(null)) continue;
    if (only && !candidates.some((candidate) => only.some((folder) => isInside(resolve(dir, candidate), folder)))) continue;
    broken.push({ line, target, otherCase: misses.find((name) => name) ?? "" });
  }
  return broken;
}

// Markdown files under a folder, for the link check. Git's own folder, node_modules, and
// inboxes are not entered, links to other folders are not followed, and `skip` holds the
// folders already covered, so overlapping folders are read once.
function markdownFiles(dir, skip, out = []) {
  const here = resolve(dir);
  if (skip.has(here.toLowerCase())) return out;
  skip.add(here.toLowerCase());
  let entries;
  try {
    entries = readdirSync(here, { withFileTypes: true });
  } catch {
    return out;
  }
  for (const entry of entries.sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0))) {
    if (LINK_SKIP.has(entry.name)) continue;
    const full = join(here, entry.name);
    if (entry.isDirectory()) markdownFiles(full, skip, out);
    else if (entry.isFile() && extname(entry.name).toLowerCase() === ".md") out.push(full);
  }
  return out;
}

// Writes an index inside one Archive folder. Nothing loads it until someone goes
// looking for history. Archived documents are listed as they are, with their
// description when they have frontmatter and their filename when they do not.
function writeArchiveIndex(archiveDir, contextRoot) {
  const entries = [];
  (function collect(dir) {
    for (const entry of readdirSync(dir).sort()) {
      if (entry.startsWith(".") || entry === "AGENTS.md") continue;
      const full = join(dir, entry);
      if (statSync(full).isDirectory()) {
        collect(full);
        continue;
      }
      const ext = extname(entry).toLowerCase();
      if (!MARKUP.has(ext)) continue;
      const rel = relative(archiveDir, full).replaceAll("\\", "/");
      const parsed = parseFrontmatter(readFileSync(full, "utf8"), ext);
      const name = parsed?.fields.name || basename(entry, ext);
      const description = parsed?.fields.description || "No frontmatter. Open it to see what it holds.";
      entries.push(`- [${name}](<${rel}>) → ${description}`);
    }
  })(archiveDir);

  const where = relative(contextRoot, archiveDir).replaceAll("\\", "/");
  const lines = [
    BEGIN,
    "",
    "# Archive Index",
    "",
    `Archived material under \`${where}\`: superseded, completed, or fully synthesized documents kept for history. Nothing here is current guidance. Open a document when you are looking for what happened.`,
    "",
    ...(entries.length ? entries : ["- Nothing archived yet."]),
    "",
    END,
  ];
  const block = lines.join("\n");
  const agentsPath = join(archiveDir, "AGENTS.md");
  let content = existsSync(agentsPath) ? readFileSync(agentsPath, "utf8") : "";
  const eol = content.includes("\r\n") ? "\r\n" : "\n";
  if (!content.trim()) content = `${block}\n`;
  else if (GUARD.test(content)) content = content.replace(GUARD, () => block);
  else content = `${content.trimEnd()}\n\n${block}\n`;
  if (eol === "\r\n") content = content.replace(/\r?\n/g, "\r\n");
  writeFileSync(agentsPath, content);
}

// Regenerates one Context directory. Returns true when it had active errors.
function processContext(contextRoot, { label, recordPass }) {
  const docs = [];
  const assets = [];
  const archives = [];
  let archivedFiles = 0;
  const broken = [];
  const errors = [];
  const warnings = [];

  function walk(dir) {
    for (const entry of readdirSync(dir).sort()) {
      if (entry.startsWith(".")) continue;
      const full = join(dir, entry);
      const rel = relative(contextRoot, full).replaceAll("\\", "/");
      if (statSync(full).isDirectory()) {
        if (entry === ARCHIVE) {
          archives.push(rel);
          archivedFiles += listFiles(full).filter((f) => f !== "AGENTS.md").length;
          if (!checkOnly) writeArchiveIndex(full, contextRoot);
          continue;
        }
        walk(full);
        continue;
      }
      if (entry === "AGENTS.md") continue;

      const ext = extname(entry).toLowerCase();
      if (!MARKUP.has(ext)) {
        assets.push(rel);
        continue;
      }

      const parsed = parseFrontmatter(readFileSync(full, "utf8"), ext);
      if (!parsed) {
        broken.push(rel);
        errors.push(`${rel}: missing frontmatter block`);
        continue;
      }

      const { fields, badLines } = parsed;
      const problems = badLines.map((line) => `unparseable frontmatter line: ${line}`);
      if (!fields.name) problems.push("missing `name`");
      if (!fields.description) problems.push("missing `description`");
      else if (fields.description.length > DESCRIPTION_MAX_CHARS) problems.push(`\`description\` over ${DESCRIPTION_MAX_CHARS} characters`);

      for (const key of ["date_created", "date_modified"]) {
        const value = fields[key];
        if (!value) {
          problems.push(`missing \`${key}\``);
          continue;
        }
        if (!isRealDate(value)) problems.push(`\`${key}\` is not a real YYYY-MM-DD date`);
      }

      if (problems.length) {
        broken.push(rel);
        for (const problem of problems) errors.push(`${rel}: ${problem}`);
        continue;
      }
      docs.push({ rel, ...fields });

      const stem = basename(entry, ext);
      if (DATE.test(stem)) warnings.push(`${rel}: the filename is only a date. Name it for its subject after the date.`);
      if (fields.description.length > DESCRIPTION_REVIEW_CHARS) {
        warnings.push(`${rel}: description is ${fields.description.length} characters. A description names the contents and the trigger, it does not summarize the findings.`);
      }
      if (fields.description.toLowerCase().startsWith(fields.name.toLowerCase())) {
        warnings.push(`${rel}: description starts by repeating the name. Say what the file holds and when it is useful.`);
      }
    }
  }

  walk(contextRoot);

  const tempPath = resolve(contextRoot, "..", TEMP);
  let tempFiles = null;
  if (existsSync(tempPath) && statSync(tempPath).isDirectory()) tempFiles = listFiles(tempPath);

  const agentsPath = join(contextRoot, "AGENTS.md");
  let content = existsSync(agentsPath) ? readFileSync(agentsPath, "utf8") : "";
  const onDisk = content;
  const eol = content.includes("\r\n") ? "\r\n" : "\n";

  // Folders outside this Context's own project that link into it, kept as paths
  // relative to the Context so they survive a clone laid out the same way.
  const rootsMatch = content.match(LINK_ROOTS);
  let linkRoots = rootsMatch ? [...rootsMatch[1].matchAll(/<([^<>]+)>/g)].map((m) => m[1]) : [];
  let scanRoots = linkRoots;
  if (recordPass && linksArg.length) {
    const named = linksArg[0] === "none" ? [] : linksArg.map((arg) => resolve(arg));
    for (const folder of named.filter((f) => isInside(f, dirname(contextRoot)))) {
      console.log(`${label}${folder} is already read, because it is in the folder that holds this Context. --links is for folders outside it.`);
    }
    scanRoots = [...new Set(named.filter((f) => !isInside(f, dirname(contextRoot))).map((f) => relative(contextRoot, f).replaceAll("\\", "/")))].sort();
    if (!checkOnly) linkRoots = scanRoots;
  }

  // Links. Inside Context every relative link is checked, Archive included, because a
  // move breaks history's links as readily as current ones. Outside it, in the folder
  // that holds this Context and the folders --links named, only links into this Context
  // or its inbox are checked: those are the ones a move, an archive, or a drain breaks,
  // and the rest of the tree is not this script's to judge.
  listings.clear();
  pendingIndex = checkOnly ? null : agentsPath;
  const seen = new Set();
  const where = (file) => relative(contextRoot, file).replaceAll("\\", "/");
  let unresolvedLinks = 0;
  const report = (file, hits) => {
    unresolvedLinks += hits.length;
    for (const hit of hits) {
      const found = hit.otherCase ? ` On disk the name is ${hit.otherCase}, in another letter case.` : "";
      warnings.push(`${where(file)}:${hit.line}: the link to ${hit.target} does not resolve.${found}`);
    }
  };
  const inside = markdownFiles(contextRoot, seen);
  for (const file of inside) {
    // A generated index is rebuilt by this script, so only authored links are read.
    const text = basename(file) === "AGENTS.md" ? readFileSync(file, "utf8").replace(GUARD, (index) => index.replace(/[^\n]/g, " ")) : null;
    report(file, brokenLinks(file, { text }));
  }
  const outside = [];
  for (const folder of [dirname(contextRoot), ...scanRoots.map((r) => resolve(contextRoot, r))]) {
    if (!existsSync(folder) || !statSync(folder).isDirectory()) {
      warnings.push(`The --links folder ${folder} does not exist. Name the folders again with --links, or forget them with --links=none.`);
      continue;
    }
    for (const file of markdownFiles(folder, seen)) {
      outside.push(file);
      report(file, brokenLinks(file, { only: [contextRoot, tempPath] }));
    }
  }
  if (unresolvedLinks) {
    warnings.push(`${unresolvedLinks} Markdown link(s) listed above do not resolve. Point each one at where its file is now. When the file is gone for good, write its name as plain text or in a code span.`);
  }
  const also = scanRoots.map((r) => ` and ${resolve(contextRoot, r)}`).join("");
  console.log(`${label}Checked links in ${inside.length} Markdown file(s) under Context, and links into it from ${outside.length} file(s) in ${dirname(contextRoot)}${also}`);

  const markerMatch = content.match(MARKER);
  let lastPass = markerMatch ? markerMatch[1] : "none";
  let cadenceDays = markerMatch ? Number(markerMatch[2]) : DEFAULT_CADENCE_DAYS;
  if (recordPass && cadenceArg !== null) cadenceDays = cadenceArg;
  if (recordPass && consolidatedOn) {
    if (errors.length) {
      errors.push("--consolidated refused: fix the frontmatter errors above, then record the pass");
    } else if (tempFiles && tempFiles.length) {
      errors.push(`--consolidated refused: ${TEMP} still holds ${tempFiles.length} file(s). Drain it, then record the pass`);
    } else if (unresolvedLinks) {
      errors.push(`--consolidated refused: ${unresolvedLinks} Markdown link(s) do not resolve. Fix them, then record the pass`);
    } else {
      lastPass = consolidatedOn;
    }
  }
  const marker = `<!-- ${SKILL_NAME}: last consolidation pass ${lastPass}, cadence ${cadenceDays} days -->`;

  const lines = [
    BEGIN,
    "",
    "# Context Index",
    "",
    "Follow any durable project instructions outside this generated block, use each description below as the trigger for what to read, and regenerate the index after any change.",
    "",
  ];

  for (const doc of docs) {
    lines.push(`- [${doc.name}](<${doc.rel}>) → ${doc.description}`);
  }

  if (broken.length) {
    lines.push("", "## Unindexed (fix frontmatter)", "");
    for (const rel of broken) lines.push(`- \`${rel}\``);
  }

  lines.push("", END);
  const rootsLine = linkRoots.length ? `<!-- ${SKILL_NAME}: also check links in ${linkRoots.map((r) => `<${r}>`).join(", ")} -->\n` : "";
  const block = `${marker}\n${rootsLine}${lines.join("\n")}`;

  content = content.replace(MARKER, "").replace(LINK_ROOTS, "");
  if (!content.trim()) content = `${block}\n`;
  else if (GUARD.test(content)) content = content.replace(GUARD, () => block);
  else content = `${content.trimEnd()}\n\n${block}\n`;
  if (eol === "\r\n") content = content.replace(/\r?\n/g, "\r\n");
  if (!checkOnly) writeFileSync(agentsPath, content);
  else if (content !== onDisk) warnings.push(`The index in ${agentsPath} is missing or out of date. A run without --check writes it.`);

  const indexBytes = Buffer.byteLength(content, "utf8");
  if (indexBytes > INDEX_WARNING_BYTES) {
    warnings.push(`${agentsPath} is ${indexBytes} bytes. Review active index scope and Context organization.`);
  }
  if (docs.length > INDEX_ENTRIES_REVIEW) {
    warnings.push(`The index lists ${docs.length} documents. Past ${INDEX_ENTRIES_REVIEW} it is too long to load on every task, so archive or split the directory.`);
  }

  const dirCounts = new Map();
  for (const doc of docs) {
    const dir = doc.rel.includes("/") ? doc.rel.slice(0, doc.rel.lastIndexOf("/")) : ".";
    dirCounts.set(dir, (dirCounts.get(dir) ?? 0) + 1);
  }
  for (const [dir, count] of [...dirCounts].sort()) {
    const where = dir === "." ? basename(contextRoot) : dir;
    if (count > DIR_FILES_SUBTOPIC) {
      warnings.push(`${where} holds ${count} active files. Past ${DIR_FILES_SUBTOPIC} it needs clearer subtopics unless it is an intentional chronological or generated collection.`);
    } else if (count > DIR_FILES_REVIEW) {
      warnings.push(`${where} holds ${count} active files. Past ${DIR_FILES_REVIEW} it is due an organization review.`);
    } else if (dir === "." && count > ROOT_FILES_REVIEW) {
      warnings.push(`${where} root holds ${count} active files. The root is for project-wide owners, so past ${ROOT_FILES_REVIEW} the rest belong in subject folders.`);
    }
  }

  const parentAgentsPath = resolve(contextRoot, "..", "AGENTS.md");
  if (existsSync(parentAgentsPath)) {
    const combinedBytes = indexBytes + Buffer.byteLength(readFileSync(parentAgentsPath, "utf8"), "utf8");
    if (combinedBytes > COMBINED_WARNING_BYTES) {
      warnings.push(`root and Context AGENTS.md total ${combinedBytes} bytes of project instructions, past ${COMBINED_WARNING_BYTES}. Move rules that are not agent-wide into topical documents, or archive.`);
    }
  }

  if (tempFiles && tempFiles.length) {
    const shown = tempFiles.slice(0, 5).join(", ") + (tempFiles.length > 5 ? ", ..." : "");
    warnings.push(`${TEMP} holds ${tempFiles.length} file(s) waiting to be drained into Context: ${shown}`);
  } else if (tempFiles) {
    warnings.push(`${TEMP} is empty. Remove it.`);
  }

  const start = checkOnly ? "Tell the session that owns this Context." : `Start it in this turn, in a fresh background subagent when one is available, given this Context and the ${SKILL_NAME} skill's Consolidation section. It ends by running the generator on ${contextRoot} with --consolidated. Only the user can defer it.`;
  if (cadenceDays > 0) {
    if (lastPass === "none") {
      warnings.push(`A consolidation pass is due: none is recorded. ${start}`);
    } else {
      const age = daysBetween(lastPass, today);
      if (age >= cadenceDays) {
        warnings.push(`A consolidation pass is due: the last one was ${age} day(s) ago, past the ${cadenceDays}-day cadence. ${start}`);
      }
    }
  }

  for (const note of ignoreInbox(tempPath)) {
    if (note.info) console.log(`${label}${note.info}`);
    else warnings.push(note.warn);
  }

  const archiveNote = archives.length ? `${archivedFiles} archived file(s) in ${archives.length} Archive folder(s)` : "no Archive folders";
  console.log(
    `${label}${checkOnly ? "Wrote nothing (--check). Found" : "Indexed"} ${docs.length} active doc(s), omitted ${assets.length} active asset(s), left ${archiveNote} out of the index, ${broken.length} unindexed in ${agentsPath}`,
  );
  for (const warning of warnings) console.warn(`${label}WARNING: ${warning}`);
  for (const error of errors) console.error(`${label}ERROR: ${error}`);
  return errors.length > 0;
}

// Every repository that holds a Context directory carries its own rule keeping Context-Inbox out
// of Git, whether or not an inbox exists yet, so a global exclude on one machine is not enough.
// Adds the rule to the repository's root .gitignore when no .gitignore in the repository supplies
// one, and returns what it did and anything still wrong. Outside a Git repository it does nothing.
function ignoreInbox(tempPath) {
  const notes = [];
  let repo = dirname(tempPath);
  while (!existsSync(join(repo, ".git"))) {
    const up = dirname(repo);
    if (up === repo) return notes;
    repo = up;
  }
  const gitignore = join(repo, ".gitignore");
  const listed = new RegExp(`^/?${TEMP}/?\s*$`, "m");
  const git = (args) => {
    try {
      return { code: 0, out: execFileSync("git", args, { cwd: repo, encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] }) };
    } catch (error) {
      return { code: typeof error.status === "number" ? error.status : -1, out: String(error.stdout || "") };
    }
  };
  // The rule must come from a .gitignore inside the repository, not from .git/info/exclude or a
  // global excludes file, and must cover the folder itself, not one path in it. Without Git, the
  // root .gitignore is read directly.
  const ownRule = () => {
    const r = git(["check-ignore", "--no-index", "-v", `${relative(repo, tempPath).replaceAll("\\", "/")}/`]);
    if (r.code === -1 || r.code === 128) return listed.test(existsSync(gitignore) ? readFileSync(gitignore, "utf8") : "");
    if (r.code !== 0) return false;
    const source = r.out.split(":")[0].replaceAll("\\", "/");
    return basename(source) === ".gitignore" && !source.startsWith(".git/") && !/^([A-Za-z]:)?\//.test(source);
  };
  if (!ownRule()) {
    const existing = existsSync(gitignore) ? readFileSync(gitignore, "utf8") : "";
    if (listed.test(existing)) {
      notes.push({ warn: `${TEMP}/ is listed in ${gitignore} but another rule overrides it. Remove the overriding rule so Git ignores the inbox.` });
    } else if (checkOnly) {
      notes.push({ warn: `${TEMP}/ is not in ${gitignore}. A run without --check adds it.` });
    } else {
      const eol = existing.includes("\r\n") ? "\r\n" : "\n";
      appendFileSync(gitignore, `${existing && !existing.endsWith("\n") ? eol : ""}${TEMP}/${eol}`);
      notes.push(ownRule()
        ? { info: `Added ${TEMP}/ to ${gitignore}` }
        : { warn: `Added ${TEMP}/ to ${gitignore}, but Git still does not ignore the inbox. Find the rule that overrides it.` });
    }
  }
  const tracked = git(["ls-files", "--", tempPath]);
  if (tracked.code === 0 && tracked.out.trim()) {
    const count = tracked.out.trim().split("\n").length;
    notes.push({ warn: `${count} file(s) in ${TEMP} are already tracked by Git, so the ignore rule does not cover them. File them into Context, then remove them with git rm.` });
  }
  return notes;
}

let failed = processContext(root, { label: "", recordPass: true });

if (nested) {
  const parent = dirname(root);
  const found = [];
  const skippedNoIndex = [];
  findNestedContexts(parent, NESTED_DEPTH + 1, found, skippedNoIndex);
  for (const contextRoot of found) {
    const label = `[${relative(parent, dirname(contextRoot)).replaceAll("\\", "/")}] `;
    if (processContext(contextRoot, { label, recordPass: false })) failed = true;
  }
  for (const contextRoot of skippedNoIndex) {
    console.log(`Skipped ${relative(parent, contextRoot).replaceAll("\\", "/")}: no index in its AGENTS.md. Run the generator there directly to start one.`);
  }
  if (!found.length && !skippedNoIndex.length) console.log(`No nested Context directories found within ${NESTED_DEPTH} levels below ${parent}`);
}

if (failed) process.exit(1);
