#!/usr/bin/env node
// Regenerate the compact active index in a Context directory's AGENTS.md,
// validate active markup frontmatter, and say when a consolidation pass is due.
//
// Usage: node scripts/index.mjs <path-to-Context> [--nested] [--consolidated[=YYYY-MM-DD]] [--cadence=<days>] [--force]
//
// The block is guard-delimited and idempotent. Content outside the block is
// preserved. Every Archive folder is skipped at any depth. The consolidation
// marker is one comment line directly above the block, outside the guards, so an
// older copy of this script leaves it alone. The script knows only its current
// name: after a rename, every existing index is regenerated by hand.

import { readFileSync, writeFileSync, existsSync, readdirSync, statSync } from "node:fs";
import { join, relative, resolve, basename, extname, dirname } from "node:path";

const SKILL_NAME = "context-memory";
const BEGIN = `<!-- BEGIN ${SKILL_NAME} index (generated, do not edit) -->`;
const END = `<!-- END ${SKILL_NAME} index -->`;
const escape = (t) => t.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
const GUARD = new RegExp(`${escape(BEGIN)}[\\s\\S]*?${escape(END)}`);
const MARKER = new RegExp(`<!-- ${escape(SKILL_NAME)}: last consolidation pass (\\d{4}-\\d{2}-\\d{2}|none), cadence (\\d+) days -->\\r?\\n?`);
const MARKUP = new Set([".md", ".html"]);
const ARCHIVE = "Archive";
const TEMP = "Context-Inbox";
const PLACEHOLDERS = new Set([".gitkeep", ".gitignore", ".DS_Store", "Thumbs.db"]);
const REQUIRED = ["name", "description", "date_created", "date_modified"];
const DATE = /^\d{4}-\d{2}-\d{2}$/;
const INDEX_WARNING_BYTES = 24 * 1024;
const INDEX_ENTRIES_REVIEW = 200;
const COMBINED_WARNING_BYTES = 32 * 1024;
// Prompts to look, not limits to enforce, so they warn and never fail the run.
const ROOT_FILES_REVIEW = 8;
const DIR_FILES_REVIEW = 12;
const DIR_FILES_SUBTOPIC = 20;
const DESCRIPTION_REVIEW_CHARS = 300;
const DESCRIPTION_MAX_CHARS = 1024;
// A consolidation pass is due on this calendar cadence even when nothing else fired,
// because drift between documents is the one thing this script cannot see.
const DEFAULT_CADENCE_DAYS = 7;
// How many directory levels below the Context's parent --nested looks for other
// Context directories that already carry an index.
const NESTED_DEPTH = 2;
const NESTED_SKIP = new Set([ARCHIVE, TEMP, "node_modules"]);
const KNOWN_FLAGS = ["--help", "--force", "--nested", "--consolidated"];

if (process.argv.includes("--help")) {
  console.log(
    "Usage: node scripts/index.mjs <path-to-Context> [--nested] [--consolidated[=YYYY-MM-DD]] [--cadence=<days>] [--force]\n" +
      "Regenerates the compact active index in <path>/AGENTS.md, validates active frontmatter, warns about Context-Inbox, directory density, and description shape, and says when a consolidation pass is due. Every Archive folder is skipped. Exits 1 on active errors.\n" +
      "  --nested            Also process every indexed Context directory in project folders up to two levels below this one's parent, each on its own.\n" +
      "  --consolidated      Record that a consolidation pass finished today, or on the given date, for this Context only. Refused while this Context has errors or a Context-Inbox with files.\n" +
      "  --cadence=<days>    Days between consolidation passes before one is due, remembered for this Context. Default 7. 0 turns the calendar check off.\n" +
      "  --force             Allow a directory not named Context.",
  );
  process.exit(0);
}

const flags = process.argv.slice(2).filter((a) => a.startsWith("--"));
const args = process.argv.slice(2).filter((a) => !a.startsWith("--"));
for (const flag of flags) {
  const ok = KNOWN_FLAGS.includes(flag) || /^--consolidated=\d{4}-\d{2}-\d{2}$/.test(flag) || /^--cadence=\d+$/.test(flag);
  if (!ok) {
    console.error(`ERROR: unknown or malformed flag ${flag}. Run --help.`);
    process.exit(1);
  }
}
const force = flags.includes("--force");
const nested = flags.includes("--nested");
const cadenceFlag = flags.find((a) => a.startsWith("--cadence="));
const cadenceArg = cadenceFlag ? Number(cadenceFlag.slice("--cadence=".length)) : null;
const consolidatedFlag = flags.find((a) => a.startsWith("--consolidated"));

const today = localDate(new Date());
let consolidatedOn = null;
if (consolidatedFlag) {
  consolidatedOn = consolidatedFlag.includes("=") ? consolidatedFlag.slice("--consolidated=".length) : today;
  if (!isRealDate(consolidatedOn) || consolidatedOn > today) {
    console.error("ERROR: --consolidated takes a real YYYY-MM-DD date no later than today");
    process.exit(1);
  }
}

const root = resolve(args[0] ?? "./Context");
if (!existsSync(root) || !statSync(root).isDirectory()) {
  console.error(`ERROR: ${root} is not a directory`);
  process.exit(1);
}
if (basename(root) !== "Context" && !force) {
  console.error(
    `ERROR: ${root} is not named Context. The index block belongs only in a Context directory's AGENTS.md. Pass --force to override.`,
  );
  process.exit(1);
}

function localDate(d) {
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;
}

function isRealDate(value) {
  const date = new Date(`${value}T00:00:00Z`);
  return DATE.test(value) && !Number.isNaN(date.getTime()) && date.toISOString().slice(0, 10) === value;
}

function daysBetween(from, to) {
  return Math.round((new Date(`${to}T00:00:00Z`) - new Date(`${from}T00:00:00Z`)) / 86400000);
}

// Reads the top-level scalar fields. Nested mappings, lists, and block scalars under
// any other key are accepted without being read, so a document may keep the fields
// it arrived with under `metadata:`. The four required fields must be single-line.
function parseFrontmatter(raw, ext) {
  let block = null;
  if (ext === ".md") {
    const match = raw.match(/^---\r?\n([\s\S]*?)\r?\n---/);
    if (match) block = match[1];
  } else {
    const match = raw.match(/^<!--\r?\n([\s\S]*?)\r?\n-->/);
    if (match) block = match[1].replace(/^---\r?\n/, "").replace(/\r?\n---$/, "");
  }
  if (block === null) return null;

  const fields = {};
  const badLines = [];
  for (const line of block.split(/\r?\n/)) {
    if (!line.trim()) continue;
    if (/^\s/.test(line) || line.startsWith("- ")) continue;
    const match = line.match(/^([\w-]+):\s*(.*)$/);
    if (!match) {
      badLines.push(line.trim());
      continue;
    }
    const key = match[1];
    const value = match[2].trim();
    if (/^[|>][+-]?$/.test(value)) {
      if (REQUIRED.includes(key)) badLines.push(`${key}: block scalars are unsupported here, use a single-line value`);
      continue;
    }
    fields[key] = value.replace(/^"(.*)"$/s, "$1").replace(/^'(.*)'$/s, "$1");
  }
  return { fields, badLines };
}

// Files under a directory, ignoring only placeholder files such as .gitkeep.
function listFiles(dir, out = []) {
  for (const entry of readdirSync(dir).sort()) {
    if (PLACEHOLDERS.has(entry)) continue;
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) listFiles(full, out);
    else out.push(entry);
  }
  return out;
}

function hasIndex(contextDir) {
  const agents = join(contextDir, "AGENTS.md");
  return existsSync(agents) && readFileSync(agents, "utf8").includes(BEGIN);
}

function findNestedContexts(parent, depth, found, skipped) {
  if (depth === 0) return;
  for (const entry of readdirSync(parent).sort()) {
    if (entry.startsWith(".") || NESTED_SKIP.has(entry)) continue;
    const full = join(parent, entry);
    let isDir = false;
    try {
      isDir = statSync(full).isDirectory();
    } catch {
      continue;
    }
    if (!isDir) continue;
    if (entry === "Context") {
      if (resolve(full) === root) continue;
      if (hasIndex(full)) found.push(full);
      else skipped.push(full);
      continue;
    }
    findNestedContexts(full, depth - 1, found, skipped);
  }
}

// Writes an index inside one Archive folder. Nothing loads it until someone goes
// looking for history. Archived documents are listed as they are, with their
// description when they have frontmatter and their filename when they do not.
function writeArchiveIndex(archiveDir, contextRoot) {
  const entries = [];
  (function collect(dir) {
    for (const entry of readdirSync(dir).sort()) {
      if (entry.startsWith(".") || entry === "AGENTS.md") continue;
      const full = join(dir, entry);
      if (statSync(full).isDirectory()) {
        collect(full);
        continue;
      }
      const ext = extname(entry).toLowerCase();
      if (!MARKUP.has(ext)) continue;
      const rel = relative(archiveDir, full).replaceAll("\\", "/");
      const parsed = parseFrontmatter(readFileSync(full, "utf8"), ext);
      const name = parsed?.fields.name || basename(entry, ext);
      const description = parsed?.fields.description || "No frontmatter. Open it to see what it holds.";
      entries.push(`- [${name}](<${rel}>) → ${description}`);
    }
  })(archiveDir);

  const where = relative(contextRoot, archiveDir).replaceAll("\\", "/");
  const lines = [
    BEGIN,
    "",
    "# Archive Index",
    "",
    `Archived material under \`${where}\`: superseded, completed, or fully synthesized documents kept for history. Nothing here is current guidance. Open a document when you are looking for what happened.`,
    "",
    ...(entries.length ? entries : ["- Nothing archived yet."]),
    "",
    END,
  ];
  const block = lines.join("\n");
  const agentsPath = join(archiveDir, "AGENTS.md");
  let content = existsSync(agentsPath) ? readFileSync(agentsPath, "utf8") : "";
  const eol = content.includes("\r\n") ? "\r\n" : "\n";
  if (!content.trim()) content = `${block}\n`;
  else if (GUARD.test(content)) content = content.replace(GUARD, () => block);
  else content = `${content.trimEnd()}\n\n${block}\n`;
  if (eol === "\r\n") content = content.replace(/\r?\n/g, "\r\n");
  writeFileSync(agentsPath, content);
}

// Regenerates one Context directory. Returns true when it had active errors.
function processContext(contextRoot, { label, recordPass }) {
  const docs = [];
  const assets = [];
  const archives = [];
  let archivedFiles = 0;
  const broken = [];
  const errors = [];
  const warnings = [];

  function walk(dir) {
    for (const entry of readdirSync(dir).sort()) {
      if (entry.startsWith(".")) continue;
      const full = join(dir, entry);
      const rel = relative(contextRoot, full).replaceAll("\\", "/");
      if (statSync(full).isDirectory()) {
        if (entry === ARCHIVE) {
          archives.push(rel);
          archivedFiles += listFiles(full).filter((f) => f !== "AGENTS.md").length;
          writeArchiveIndex(full, contextRoot);
          continue;
        }
        walk(full);
        continue;
      }
      if (entry === "AGENTS.md") continue;

      const ext = extname(entry).toLowerCase();
      if (!MARKUP.has(ext)) {
        assets.push(rel);
        continue;
      }

      const parsed = parseFrontmatter(readFileSync(full, "utf8"), ext);
      if (!parsed) {
        broken.push(rel);
        errors.push(`${rel}: missing frontmatter block`);
        continue;
      }

      const { fields, badLines } = parsed;
      const problems = badLines.map((line) => `unparseable frontmatter line: ${line}`);
      if (!fields.name) problems.push("missing `name`");
      if (!fields.description) problems.push("missing `description`");
      else if (fields.description.length > DESCRIPTION_MAX_CHARS) problems.push(`\`description\` over ${DESCRIPTION_MAX_CHARS} characters`);

      for (const key of ["date_created", "date_modified"]) {
        const value = fields[key];
        if (!value) {
          problems.push(`missing \`${key}\``);
          continue;
        }
        if (!isRealDate(value)) problems.push(`\`${key}\` is not a real YYYY-MM-DD date`);
      }

      if (problems.length) {
        broken.push(rel);
        for (const problem of problems) errors.push(`${rel}: ${problem}`);
        continue;
      }
      docs.push({ rel, ...fields });

      const stem = basename(entry, ext);
      if (DATE.test(stem)) warnings.push(`${rel}: the filename is only a date. Name it for its subject after the date.`);
      if (fields.description.length > DESCRIPTION_REVIEW_CHARS) {
        warnings.push(`${rel}: description is ${fields.description.length} characters. A description names the contents and the trigger, it does not summarize the findings.`);
      }
      if (fields.description.toLowerCase().startsWith(fields.name.toLowerCase())) {
        warnings.push(`${rel}: description starts by repeating the name. Say what the file holds and when it is useful.`);
      }
    }
  }

  walk(contextRoot);

  const tempPath = resolve(contextRoot, "..", TEMP);
  let tempFiles = null;
  if (existsSync(tempPath) && statSync(tempPath).isDirectory()) tempFiles = listFiles(tempPath);

  const agentsPath = join(contextRoot, "AGENTS.md");
  let content = existsSync(agentsPath) ? readFileSync(agentsPath, "utf8") : "";
  const eol = content.includes("\r\n") ? "\r\n" : "\n";

  const markerMatch = content.match(MARKER);
  let lastPass = markerMatch ? markerMatch[1] : "none";
  let cadenceDays = markerMatch ? Number(markerMatch[2]) : DEFAULT_CADENCE_DAYS;
  if (recordPass && cadenceArg !== null) cadenceDays = cadenceArg;
  if (recordPass && consolidatedOn) {
    if (errors.length) {
      errors.push("--consolidated refused: fix the frontmatter errors above, then record the pass");
    } else if (tempFiles && tempFiles.length) {
      errors.push(`--consolidated refused: ${TEMP} still holds ${tempFiles.length} file(s). Drain it, then record the pass`);
    } else {
      lastPass = consolidatedOn;
    }
  }
  const marker = `<!-- ${SKILL_NAME}: last consolidation pass ${lastPass}, cadence ${cadenceDays} days -->`;

  const lines = [
    BEGIN,
    "",
    "# Context Index",
    "",
    "Follow any durable project instructions outside this generated block, use each description below as the trigger for what to read, and regenerate the index after any change.",
    "",
  ];

  for (const doc of docs) {
    lines.push(`- [${doc.name}](<${doc.rel}>) → ${doc.description}`);
  }

  if (broken.length) {
    lines.push("", "## Unindexed (fix frontmatter)", "");
    for (const rel of broken) lines.push(`- \`${rel}\``);
  }

  lines.push("", END);
  const block = `${marker}\n${lines.join("\n")}`;

  content = content.replace(MARKER, "");
  if (!content.trim()) content = `${block}\n`;
  else if (GUARD.test(content)) content = content.replace(GUARD, () => block);
  else content = `${content.trimEnd()}\n\n${block}\n`;
  if (eol === "\r\n") content = content.replace(/\r?\n/g, "\r\n");
  writeFileSync(agentsPath, content);

  const indexBytes = Buffer.byteLength(content, "utf8");
  if (indexBytes > INDEX_WARNING_BYTES) {
    warnings.push(`${agentsPath} is ${indexBytes} bytes. Review active index scope and Context organization.`);
  }
  if (docs.length > INDEX_ENTRIES_REVIEW) {
    warnings.push(`The index lists ${docs.length} documents. Past ${INDEX_ENTRIES_REVIEW} it is too long to load on every task, so archive or split the directory.`);
  }

  const dirCounts = new Map();
  for (const doc of docs) {
    const dir = doc.rel.includes("/") ? doc.rel.slice(0, doc.rel.lastIndexOf("/")) : ".";
    dirCounts.set(dir, (dirCounts.get(dir) ?? 0) + 1);
  }
  for (const [dir, count] of [...dirCounts].sort()) {
    const where = dir === "." ? basename(contextRoot) : dir;
    if (count > DIR_FILES_SUBTOPIC) {
      warnings.push(`${where} holds ${count} active files. Past ${DIR_FILES_SUBTOPIC} it needs clearer subtopics unless it is an intentional chronological or generated collection.`);
    } else if (count > DIR_FILES_REVIEW) {
      warnings.push(`${where} holds ${count} active files. Past ${DIR_FILES_REVIEW} it is due an organization review.`);
    } else if (dir === "." && count > ROOT_FILES_REVIEW) {
      warnings.push(`${where} root holds ${count} active files. The root is for project-wide owners, so past ${ROOT_FILES_REVIEW} the rest belong in subject folders.`);
    }
  }

  const parentAgentsPath = resolve(contextRoot, "..", "AGENTS.md");
  if (existsSync(parentAgentsPath)) {
    const combinedBytes = indexBytes + Buffer.byteLength(readFileSync(parentAgentsPath, "utf8"), "utf8");
    if (combinedBytes > COMBINED_WARNING_BYTES) {
      warnings.push(`root and Context AGENTS.md total ${combinedBytes} bytes of project instructions, past ${COMBINED_WARNING_BYTES}. Move rules that are not agent-wide into topical documents, or archive.`);
    }
  }

  if (tempFiles && tempFiles.length) {
    const shown = tempFiles.slice(0, 5).join(", ") + (tempFiles.length > 5 ? ", ..." : "");
    warnings.push(`${TEMP} holds ${tempFiles.length} file(s) waiting to be drained into Context: ${shown}`);
  } else if (tempFiles) {
    warnings.push(`${TEMP} is empty. Remove it.`);
  }

  const record = `run the generator on ${contextRoot} with --consolidated when it is done`;
  if (cadenceDays > 0) {
    if (lastPass === "none") {
      warnings.push(`No consolidation pass is recorded. Run one and ${record}.`);
    } else {
      const age = daysBetween(lastPass, today);
      if (age >= cadenceDays) {
        warnings.push(`The last consolidation pass was ${age} day(s) ago, past the ${cadenceDays}-day cadence. A pass is due, then ${record}.`);
      }
    }
  }

  const archiveNote = archives.length ? `${archivedFiles} archived file(s) in ${archives.length} Archive folder(s)` : "no Archive folders";
  console.log(
    `${label}Indexed ${docs.length} active doc(s), omitted ${assets.length} active asset(s), skipped ${archiveNote}, ${broken.length} unindexed in ${agentsPath}`,
  );
  for (const warning of warnings) console.warn(`${label}WARNING: ${warning}`);
  for (const error of errors) console.error(`${label}ERROR: ${error}`);
  return errors.length > 0;
}

let failed = processContext(root, { label: "", recordPass: true });

if (nested) {
  const parent = dirname(root);
  const found = [];
  const skippedNoIndex = [];
  findNestedContexts(parent, NESTED_DEPTH + 1, found, skippedNoIndex);
  for (const contextRoot of found) {
    const label = `[${relative(parent, dirname(contextRoot)).replaceAll("\\", "/")}] `;
    if (processContext(contextRoot, { label, recordPass: false })) failed = true;
  }
  for (const contextRoot of skippedNoIndex) {
    console.log(`Skipped ${relative(parent, contextRoot).replaceAll("\\", "/")}: no index in its AGENTS.md. Run the generator there directly to start one.`);
  }
  if (!found.length && !skippedNoIndex.length) console.log(`No nested Context directories found within ${NESTED_DEPTH} levels below ${parent}`);
}

if (failed) process.exit(1);
